// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3925.Rafiki.subsystems;

import org.usfirst.frc3925.Rafiki.RobotMap;
import org.usfirst.frc3925.Rafiki.commands.ElevatorRun;
import org.usfirst.frc3925.Rafiki.helper.Constants;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Elevator extends Subsystem {
	public static enum State {
		IDLE, ZERO;
	}
	protected static final double
	MAX_HEIGHT = Constants.ELEVATOR_MAX_HEIGHT,
	TOLERANCE = Constants.ELEVATOR_TOLERANCE;
	
	protected double currentPos;
	protected State state = State.IDLE;
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Encoder encoderElevator = RobotMap.elevatorEncoderElevator;
    SpeedController motorElevatorA = RobotMap.elevatorMotorElevatorA;
    PIDController elevatorPID = RobotMap.elevatorElevatorPID;
    SpeedController motorElevatorB = RobotMap.elevatorMotorElevatorB;
    DigitalInput elevatorSwitch = RobotMap.elevatorElevatorSwitch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public void run() {
    	switch (state) {
		case IDLE:
			
			break;

		case ZERO:
			
			break;
			
		default:
			break;
		}
    }
    
    public void setState(State state) {
    	this.state = state;
    }
    
    public void logData() {
    	SmartDashboard.putString("ElevatorState", state.toString());
    }
    
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new ElevatorRun());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

